server:
  port: 8082
  
spring:
  datasource:
     url: jdbc:mysql://localhost:5432/microservices
     username: root
     password: Mysql@123
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true      